eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
          defaultZone: https://etmdiscovery.azurewebsites.net
      instance:
        preferIpAddress: true
